In [1]:
import numpy as np

# Reshaping an array

## In place 
Changinng the shape of an ndarray is as simple as setting its shape attribute. However,the arrays size must remain the same

In [2]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [3]:
g.shape = (6, 4)
print(g)
print("Rank:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


In [4]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


## reshape
The reshape function returns a new ndarray object pointing at the same data. This means that modifying one array will also modify the other

In [8]:
g2 = g.reshape(4,6)
print(g2)
print("Rank:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Rank: 2


Set item at row 1, col 2 to 999

In [11]:
g2[1][2] = 999
g2[2,3] = 888	# same as above
print(g2)
print(g)

[[  0   1   2   3   4   5]
 [  6   7 999   9  10  11]
 [ 12  13  14 888  16  17]
 [ 18  19  20  21  22  23]]
[[[  0   1   2   3]
  [  4   5   6   7]
  [999   9  10  11]]

 [[ 12  13  14 888]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


## ravel
Finally, the ravel function returnns a new one-d mdarray the also points to the same data:

In [12]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14, 888,  16,  17,  18,  19,  20,  21,  22,  23])